const REFERENCE_EXPERIENCES = [
  {
    title: "Head - Project Management, Operations & Transformation",
    company: "Apex CoVantage",
    location: "Hyderabad",
    current: true,
    start_date: "07/2025",
    end_date: "",
    description: "Project Management, Operations & Transformation | Jul 2025 - Present\nLead publishing and content transformation programs for global clients. Lead delivery governance, workforce planning, operational KPIs, and client satisfaction initiatives. Drive GenAI-led transformation initiatives improving operational efficiency, scalability, and delivery predictability. Lead cross-functional teams across project management, production, quality, and technology functions. Manage strategic vendor relationships, outsourcing partners, and third-party service providers to ensure SLA compliance, delivery excellence, and operational efficiency. Partner with leadership teams on operational strategy, transformation initiatives, and account growth.",
  },
  {
    title: "Assistant Director",
    company: "eVC Tech",
    location: "Pondicherry",
    current: false,
    start_date: "02/2025",
    end_date: "06/2025",
    description: "Client Success & Operations\nLed client success strategy and operational governance across multiple accounts. Coordinated with external partners and service providers to support operational delivery, process improvements, and customer success objectives. Managed escalations, delivery reviews, and process optimization initiatives. Improved turnaround time, cost efficiency, and delivery coordination.",
  },
  {
    title: "Senior Account Manager",
    company: "Straive",
    location: "Pondicherry",
    current: false,
    start_date: "05/2017",
    end_date: "09/2024",
    description: "Client Success\nManaged strategic account governance for global publishing clients. Led delivery teams ensuring SLA adherence and service excellence. Championed AI/ML automation initiatives achieving 25% turnaround time reduction and 15% operational cost savings. Improved operational predictability through enterprise risk and governance frameworks.",
  },
  {
    title: "Senior Manager / Manager",
    company: "MPS Ltd",
    location: "Bangalore",
    current: false,
    start_date: "05/2008",
    end_date: "04/2017",
    description: "Operations\nDirected publishing operations across global delivery pipelines. Standardized workflows, dashboards, and operational tracking mechanisms supporting scalable growth.",
  },
  {
    title: "BU Head - Operations & Sales",
    company: "Reverend Technologies Pvt. Ltd.",
    location: "Bangalore",
    current: false,
    start_date: "09/2013",
    end_date: "05/2015",
    description: "Managed business operations, delivery strategy, and client engagement initiatives. Supported account growth, operational efficiency, and customer retention programs.",
  },
  {
    title: "Assistant Manager",
    company: "Aptara, Inc",
    location: "New Delhi",
    current: false,
    start_date: "02/2000",
    end_date: "04/2008",
    description: "Planning\nDirected publishing operations across global delivery pipelines. Standardized workflows, dashboards, and operational tracking mechanisms supporting scalable growth.",
  },
  {
    title: "Senior Ramp-up Executive",
    company: "SourceHOV",
    location: "Chennai",
    current: false,
    start_date: "12/1995",
    end_date: "01/2000",
    description: "Delivered workforce ramp-up programs supporting client operations.\nSelected Executive Achievements: Achieved 25% turnaround time reduction through AI/ML automation initiatives. Delivered 15% operational cost optimization through process standardization and technology adoption. Received Circle of Champion Award - Straive (2023) for enterprise people leadership. Built and scaled high-performing teams and large workforce ramp-up operations. Led ISO-certified quality, compliance, and governance programs.",
  },
];

const REFERENCE_EDUCATION = [
  {
    school: "Dayananda Sagar University",
    degree: "Master of Business Administration (M.B.A.)",
    field_of_study: "Information Technology",
    gpa: "7.5",
    start_date: "2024",
    end_date: "2025",
  },
  {
    school: "Annamalai University",
    degree: "Master of Arts (M.A.)",
    field_of_study: "Public Administration",
    gpa: "5",
    start_date: "1999",
    end_date: "2000",
  },
  {
    school: "Madras University",
    degree: "Bachelor of Arts (B.A.)",
    field_of_study: "Economics",
    gpa: "5",
    start_date: "1991",
    end_date: "1994",
  },
];

export { REFERENCE_EXPERIENCES, REFERENCE_EDUCATION };
